export const KATA_AGENT_ERROR_CODES = [
  "INVALID_MODEL_JSON",
  "SCHEMA_VALIDATION_FAILED",
  "PROVIDER_TRANSIENT",
  "PLUGIN_NETWORK_TRANSIENT",
  "MISSING_SECRET",
  "FORBIDDEN_WRITE_SCOPE",
  "UNRESOLVED_P0_GAP",
  "INVALID_WORKFLOW_DEFINITION",
  "SCHEMA_REFERENCE_NOT_FOUND",
  "ARTIFACT_HASH_MISMATCH",
  "RUN_CANCELLED",
] as const;

export type KataAgentErrorCode = (typeof KATA_AGENT_ERROR_CODES)[number];

const RETRYABLE_CODES = new Set<KataAgentErrorCode>([
  "INVALID_MODEL_JSON",
  "SCHEMA_VALIDATION_FAILED",
  "PROVIDER_TRANSIENT",
  "PLUGIN_NETWORK_TRANSIENT",
]);

export function isRetryable(code: KataAgentErrorCode): boolean {
  return RETRYABLE_CODES.has(code);
}
