// ---------------------------------------------------------------------------
// @kata-agent/conversation-agent — QA Workflow tools. The conversation layer
// owns only tool schemas and permission checks; a controller injected by the
// host application performs real WorkflowEngine/SkillRunner operations.
// ---------------------------------------------------------------------------
import type { ConversationTool, ToolResult, ToolContext } from "../types";

export interface WorkflowToolRun {
  runId: string;
  workflowName: string;
  status: string;
  currentNode?: string;
  project?: string;
  feature?: string;
  featureDir?: string;
}

export interface WorkflowStartInput {
  workflowName: string;
  project?: string;
  feature?: string;
  sourceUrl?: string;
  runId?: string;
  mode?: "mock" | "real";
  inputs?: Record<string, string>;
}

export interface WorkflowRunLookupInput {
  runId: string;
  project?: string;
  feature?: string;
  featureDir?: string;
  mode?: "mock" | "real";
}

export interface WorkflowFindRunsInput {
  project?: string;
  workflowName?: string;
}

export interface WorkflowToolController {
  start(input: WorkflowStartInput, context: ToolContext): Promise<WorkflowToolRun>;
  status(
    input: WorkflowRunLookupInput,
    context: ToolContext,
  ): Promise<WorkflowToolRun>;
  resume(
    input: WorkflowRunLookupInput,
    context: ToolContext,
  ): Promise<WorkflowToolRun>;
  findRuns(
    input: WorkflowFindRunsInput,
    context: ToolContext,
  ): Promise<{ runs: WorkflowToolRun[] }>;
}

// ---------------------------------------------------------------------------
// Helper: build a standard INVALID_INPUT error result
// ---------------------------------------------------------------------------

function missingParam(name: string): ToolResult {
  return {
    ok: false,
    summary: `Missing required parameter: "${name}"`,
    error: {
      code: "INVALID_INPUT",
      retryable: false,
      message: `The '${name}' parameter is required.`,
    },
  };
}

function notWired(action: string): ToolResult {
  return {
    ok: false,
    summary: `Workflow tool is not wired: ${action}`,
    error: {
      code: "ACTION_NOT_WIRED",
      retryable: false,
      message:
        "The host application must inject a WorkflowToolController before workflow tools can run.",
    },
  };
}

function executionError(action: string, error: unknown): ToolResult {
  const message = error instanceof Error ? error.message : String(error);
  return {
    ok: false,
    summary: `Workflow tool failed: ${action}`,
    error: {
      code: "WORKFLOW_TOOL_ERROR",
      retryable: false,
      message,
    },
  };
}

function optionalString(value: unknown): string | undefined {
  const text = typeof value === "string" ? value.trim() : "";
  return text ? text : undefined;
}

function mode(value: unknown): "mock" | "real" | undefined {
  if (value === "mock" || value === "real") return value;
  return undefined;
}

function stringRecord(value: unknown): Record<string, string> | undefined {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return undefined;
  }
  const record: Record<string, string> = {};
  for (const [key, item] of Object.entries(value)) {
    if (typeof item === "string") record[key] = item;
  }
  return record;
}

// ---------------------------------------------------------------------------
// Tool factory
// ---------------------------------------------------------------------------

/**
 * Create the four QA workflow tools.
 *
 * - workflow.start      — Start a new QA workflow run (mock)
 * - workflow.status     — Check the status of a workflow run (mock)
 * - workflow.resume     — Resume a workflow run (mock)
 * - workflow.find_runs  — Find recent workflow runs (mock)
 *
 * All tools use permission "safe" and belong to the "qa-workflows" toolset.
 */
export function createWorkflowTools(
  controller?: WorkflowToolController,
): Record<string, ConversationTool> {
  const startTool: ConversationTool = {
    name: "workflow_start",
    description:
      "Start a QA workflow. Accepts workflow name, optional project, " +
      "feature, and source URL. Returns a mock run ID.",
    inputSchema: {
      type: "object",
      properties: {
        workflowName: {
          type: "string",
          description: "Name of the workflow to start (e.g. 'qa-review')",
        },
        project: {
          type: "string",
          description: "Optional project name",
        },
        feature: {
          type: "string",
          description: "Optional feature or branch name",
        },
        sourceUrl: {
          type: "string",
          description: "Optional URL to the source (e.g. PR URL)",
        },
        runId: {
          type: "string",
          description: "Optional run ID. Generated by the host when omitted.",
        },
        mode: {
          type: "string",
          enum: ["mock", "real"],
          description: "Runtime mode. Defaults to mock in chat mode.",
        },
        inputs: {
          type: "object",
          additionalProperties: { type: "string" },
          description: "Optional workflow-specific string inputs.",
        },
      },
      required: ["workflowName"],
    },
    permission: "safe",
    toolset: "qa-workflows",

    async execute(
      input: Record<string, unknown>,
      context: ToolContext,
    ): Promise<ToolResult> {
      const workflowName = String(input.workflowName ?? "").trim();

      if (!workflowName) {
        return missingParam("workflowName");
      }
      if (!controller) return notWired("workflow_start");

      try {
        const run = await controller.start(
          {
            workflowName,
            project: optionalString(input.project),
            feature: optionalString(input.feature),
            sourceUrl: optionalString(input.sourceUrl),
            runId: optionalString(input.runId),
            mode: mode(input.mode),
            inputs: stringRecord(input.inputs),
          },
          context,
        );
        return {
          ok: true,
          summary: `Started workflow ${run.workflowName} (run ID: ${run.runId}, status: ${run.status})`,
          data: run,
        };
      } catch (error) {
        return executionError("workflow_start", error);
      }
    },
  };

  const statusTool: ConversationTool = {
    name: "workflow_status",
    description:
      "Check the current status of a workflow run. Returns a mock status.",
    inputSchema: {
      type: "object",
      properties: {
        runId: {
          type: "string",
          description: "The run ID to check",
        },
        project: { type: "string" },
        feature: { type: "string" },
        featureDir: {
          type: "string",
          description: "Feature workspace directory when project/feature is unknown.",
        },
      },
      required: ["runId"],
    },
    permission: "safe",
    toolset: "qa-workflows",

    async execute(
      input: Record<string, unknown>,
      context: ToolContext,
    ): Promise<ToolResult> {
      const runId = String(input.runId ?? "").trim();

      if (!runId) {
        return missingParam("runId");
      }
      if (!controller) return notWired("workflow_status");

      try {
        const run = await controller.status(
          {
            runId,
            project: optionalString(input.project),
            feature: optionalString(input.feature),
            featureDir: optionalString(input.featureDir),
          },
          context,
        );
        return {
          ok: true,
          summary: `Status for run ${runId}: ${run.status}`,
          data: run,
        };
      } catch (error) {
        return executionError("workflow_status", error);
      }
    },
  };

  const resumeTool: ConversationTool = {
    name: "workflow_resume",
    description:
      "Resume a paused workflow run. Returns a mock success response.",
    inputSchema: {
      type: "object",
      properties: {
        runId: {
          type: "string",
          description: "The run ID to resume",
        },
        project: { type: "string" },
        feature: { type: "string" },
        featureDir: {
          type: "string",
          description: "Feature workspace directory when project/feature is unknown.",
        },
        mode: {
          type: "string",
          enum: ["mock", "real"],
          description: "Runtime mode. Defaults to mock in chat mode.",
        },
      },
      required: ["runId"],
    },
    permission: "safe",
    toolset: "qa-workflows",

    async execute(
      input: Record<string, unknown>,
      context: ToolContext,
    ): Promise<ToolResult> {
      const runId = String(input.runId ?? "").trim();

      if (!runId) {
        return missingParam("runId");
      }
      if (!controller) return notWired("workflow_resume");

      try {
        const run = await controller.resume(
          {
            runId,
            project: optionalString(input.project),
            feature: optionalString(input.feature),
            featureDir: optionalString(input.featureDir),
            mode: mode(input.mode),
          },
          context,
        );
        return {
          ok: true,
          summary: `Run ${run.runId} resumed with status: ${run.status}`,
          data: run,
        };
      } catch (error) {
        return executionError("workflow_resume", error);
      }
    },
  };

  const findRunsTool: ConversationTool = {
    name: "workflow_find_runs",
    description:
      "Find recent workflow runs, optionally filtered by project or " +
      "workflow name. Returns a mock list.",
    inputSchema: {
      type: "object",
      properties: {
        project: {
          type: "string",
          description: "Optional project filter",
        },
        workflowName: {
          type: "string",
          description: "Optional workflow name filter",
        },
      },
      required: [],
    },
    permission: "safe",
    toolset: "qa-workflows",

    async execute(
      input: Record<string, unknown>,
      context: ToolContext,
    ): Promise<ToolResult> {
      if (!controller) return notWired("workflow_find_runs");

      try {
        const result = await controller.findRuns(
          {
            project: optionalString(input.project),
            workflowName: optionalString(input.workflowName),
          },
          context,
        );
        return {
          ok: true,
          summary: `Found ${result.runs.length} workflow run(s)`,
          data: result,
        };
      } catch (error) {
        return executionError("workflow_find_runs", error);
      }
    },
  };

  return {
    workflow_start: startTool,
    workflow_status: statusTool,
    workflow_resume: resumeTool,
    workflow_find_runs: findRunsTool,
  };
}
